<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
  'key' => 'group_57fa619524877',
  'title' => 'Avances',
  'fields' => array (
    array (
      'key' => 'field_57fa660ce5e3f',
      'label' => 'Avances',
      'name' => 'avances',
      'type' => 'flexible_content',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'button_label' => 'Add Avances',
      'min' => '',
      'max' => '',
      'layouts' => array (
        array (
          'key' => '57fa661c9ecb7',
          'name' => 'avances',
          'label' => 'Avances',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_57fa61d21226a',
              'label' => 'Titulo de la obra',
              'name' => 'titulo',
              'type' => 'text',
              'instructions' => '',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_57fa622a1226b',
              'label' => 'Nombre de la obra',
              'name' => 'nombre',
              'type' => 'text',
              'instructions' => 'Este nombre se muestra en la barra de navegacion',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_57fa62321226c',
              'label' => 'Galeria',
              'name' => 'galeria',
              'type' => 'flexible_content',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'button_label' => 'Add Row',
              'min' => '',
              'max' => '',
              'layouts' => array (
                array (
                  'key' => '57fa629530e3c',
                  'name' => 'galeria',
                  'label' => 'Nueva Galeria',
                  'display' => 'block',
                  'sub_fields' => array (
                    array (
                      'key' => 'field_57fa629b1226d',
                      'label' => 'Titulo Galeria',
                      'name' => 'titulo_galeria',
                      'type' => 'text',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'maxlength' => '',
                    ),
                    array (
                      'key' => 'field_57fa62ae1226e',
                      'label' => 'Imagenes Galeria',
                      'name' => 'imagenes_galeria',
                      'type' => 'gallery',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'min' => '',
                      'max' => '',
                      'insert' => 'append',
                      'library' => 'all',
                      'min_width' => '',
                      'min_height' => '',
                      'min_size' => '',
                      'max_width' => '',
                      'max_height' => '',
                      'max_size' => '',
                      'mime_types' => '',
                    ),
                  ),
                  'min' => '',
                  'max' => '',
                ),
              ),
            ),
          ),
          'min' => '',
          'max' => '',
        ),
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'page',
        'operator' => '==',
        'value' => '45',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'acf_after_title',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array (
  'key' => 'group_57f5bba492d9e',
  'title' => 'Page Blocks',
  'fields' => array (
    array (
      'key' => 'field_57f8583a756c7',
      'label' => 'Project Masterhead',
      'name' => 'project_masterhead',
      'type' => 'flexible_content',
      'instructions' => '',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'button_label' => 'Add Masterhead',
      'min' => '',
      'max' => '',
      'layouts' => array (
        array (
          'key' => '57f85867e151b',
          'name' => 'masterhead_del_proyecto',
          'label' => 'Masterhead del Proyecto',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_57f858b0756c9',
              'label' => 'Tipo',
              'name' => 'tipo',
              'type' => 'text',
              'instructions' => '',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => 'Add title',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_57f858d7756ca',
              'label' => 'introduccion',
              'name' => 'introduccion',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'basic',
              'media_upload' => 1,
            ),
            array (
              'key' => 'field_57f85915756cb',
              'label' => 'Imagen de fondo',
              'name' => 'imagen_de_fondo',
              'type' => 'image',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'return_format' => 'array',
              'preview_size' => 'thumbnail',
              'library' => 'all',
              'min_width' => '',
              'min_height' => '',
              'min_size' => '',
              'max_width' => '',
              'max_height' => '',
              'max_size' => '',
              'mime_types' => '',
            ),
          ),
          'min' => '1',
          'max' => '1',
        ),
      ),
    ),
    array (
      'key' => 'field_57f6ff88fc68a',
      'label' => 'Projectos',
      'name' => 'projects',
      'type' => 'flexible_content',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'button_label' => 'Add Projecto',
      'min' => '',
      'max' => '',
      'layouts' => array (
        array (
          'key' => '57f6ff9c13291',
          'name' => 'project',
          'label' => 'Projecto',
          'display' => 'row',
          'sub_fields' => array (
            array (
              'key' => 'field_57f98df393f61',
              'label' => 'Nombre proyecto',
              'name' => 'nombre_proyecto',
              'type' => 'text',
              'instructions' => 'Nombre del proyecto como quieres que aparezca en la barra de navegacion de proyectos',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_57f7085fa5b93',
              'label' => 'Titulo',
              'name' => 'title',
              'type' => 'text',
              'instructions' => '',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_57f7e0df65c78',
              'label' => 'Añadir Logo de proyecto',
              'name' => 'anadir_logo_proyecto',
              'type' => 'true_false',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'message' => '',
              'default_value' => 0,
            ),
            array (
              'key' => 'field_57f7e17365c79',
              'label' => 'Logo de proyecto',
              'name' => 'logo_proyecto',
              'type' => 'image',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_57f7e0df65c78',
                    'operator' => '==',
                    'value' => '1',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'return_format' => 'url',
              'preview_size' => 'thumbnail',
              'library' => 'all',
              'min_width' => '',
              'min_height' => '',
              'min_size' => '',
              'max_width' => '',
              'max_height' => '',
              'max_size' => '',
              'mime_types' => '',
            ),
            array (
              'key' => 'field_57f70e79a577f',
              'label' => 'Descripcion',
              'name' => 'description',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
            ),
            array (
              'key' => 'field_57f985260f97e',
              'label' => 'Metadatos',
              'name' => 'metadatos',
              'type' => 'repeater',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'collapsed' => '',
              'min' => '',
              'max' => '',
              'layout' => 'block',
              'button_label' => 'Add Row',
              'sub_fields' => array (
                array (
                  'key' => 'field_57f985470f97f',
                  'label' => 'nombre',
                  'name' => 'nombre',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                ),
                array (
                  'key' => 'field_57f985650f980',
                  'label' => 'valor',
                  'name' => 'valor',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                ),
              ),
            ),
            array (
              'key' => 'field_57f70008fc68b',
              'label' => 'Galeria',
              'name' => 'gallery',
              'type' => 'gallery',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'min' => '',
              'max' => '',
              'insert' => 'append',
              'library' => 'all',
              'min_width' => '',
              'min_height' => '',
              'min_size' => '',
              'max_width' => '',
              'max_height' => '',
              'max_size' => '',
              'mime_types' => '',
            ),
            array (
              'key' => 'field_57f7b2d9defe8',
              'label' => 'Ficha Tecnica',
              'name' => 'ficha_tecnica',
              'type' => 'flexible_content',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'button_label' => 'Add Ficha',
              'min' => '',
              'max' => '',
              'layouts' => array (
                array (
                  'key' => '57f7b30c21bf6',
                  'name' => 'bloque_ficha_tecnica',
                  'label' => 'Bloque ficha Tecnica',
                  'display' => 'block',
                  'sub_fields' => array (
                    array (
                      'key' => 'field_57f7c081d4621',
                      'label' => 'Titulo ficha',
                      'name' => 'titulo_ficha',
                      'type' => 'text',
                      'instructions' => '',
                      'required' => 1,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'maxlength' => '',
                    ),
                    array (
                      'key' => 'field_57f7c9a8eee07',
                      'label' => 'Columnas',
                      'name' => 'columnas',
                      'type' => 'repeater',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'collapsed' => '',
                      'min' => '',
                      'max' => 3,
                      'layout' => 'block',
                      'button_label' => 'Nueva Columna',
                      'sub_fields' => array (
                        array (
                          'key' => 'field_57fa8334a50e4',
                          'label' => 'Celda',
                          'name' => 'celda',
                          'type' => 'flexible_content',
                          'instructions' => '',
                          'required' => 0,
                          'conditional_logic' => 0,
                          'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                          ),
                          'button_label' => 'Nueva Celda',
                          'min' => '',
                          'max' => '',
                          'layouts' => array (
                            array (
                              'key' => '57fa834507cde',
                              'name' => 'nueva_celda',
                              'label' => 'Nueva Celda',
                              'display' => 'block',
                              'sub_fields' => array (
                                array (
                                  'key' => 'field_57f7e26d5078e',
                                  'label' => 'Tipo dato columna',
                                  'name' => 'tipo_dato_columna',
                                  'type' => 'select',
                                  'instructions' => '',
                                  'required' => 0,
                                  'conditional_logic' => 0,
                                  'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                  ),
                                  'choices' => array (
                                    'tabla' => 'tabla',
                                    'lista' => 'Lista definida',
                                    'lista_basica' => 'Lista Basica',
                                  ),
                                  'default_value' => array (
                                    0 => 'tabla',
                                  ),
                                  'allow_null' => 0,
                                  'multiple' => 0,
                                  'ui' => 0,
                                  'ajax' => 0,
                                  'return_format' => 'value',
                                  'placeholder' => '',
                                ),
                                array (
                                  'key' => 'field_57fa800a30ae5',
                                  'label' => 'Lista Basica',
                                  'name' => 'lista_basica',
                                  'type' => 'repeater',
                                  'instructions' => '',
                                  'required' => 0,
                                  'conditional_logic' => array (
                                    array (
                                      array (
                                        'field' => 'field_57f7e26d5078e',
                                        'operator' => '==',
                                        'value' => 'lista_basica',
                                      ),
                                    ),
                                  ),
                                  'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                  ),
                                  'collapsed' => '',
                                  'min' => '',
                                  'max' => '',
                                  'layout' => 'block',
                                  'button_label' => 'Add Lista',
                                  'sub_fields' => array (
                                    array (
                                      'key' => 'field_57fa803130ae6',
                                      'label' => 'valor',
                                      'name' => 'valor',
                                      'type' => 'text',
                                      'instructions' => '',
                                      'required' => 0,
                                      'conditional_logic' => 0,
                                      'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                      ),
                                      'default_value' => '',
                                      'placeholder' => '',
                                      'prepend' => '',
                                      'append' => '',
                                      'maxlength' => '',
                                    ),
                                  ),
                                ),
                                array (
                                  'key' => 'field_57f7ba79defea',
                                  'label' => 'horizontal',
                                  'name' => 'horizontal',
                                  'type' => 'repeater',
                                  'instructions' => '',
                                  'required' => 0,
                                  'conditional_logic' => array (
                                    array (
                                      array (
                                        'field' => 'field_57f7e26d5078e',
                                        'operator' => '==',
                                        'value' => 'tabla',
                                      ),
                                    ),
                                  ),
                                  'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                  ),
                                  'collapsed' => '',
                                  'min' => '',
                                  'max' => '',
                                  'layout' => 'block',
                                  'button_label' => 'Add Row',
                                  'sub_fields' => array (
                                    array (
                                      'key' => 'field_57f7ba90defeb',
                                      'label' => 'Titulo',
                                      'name' => 'title',
                                      'type' => 'text',
                                      'instructions' => '',
                                      'required' => 0,
                                      'conditional_logic' => 0,
                                      'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                      ),
                                      'default_value' => '',
                                      'placeholder' => '',
                                      'prepend' => '',
                                      'append' => '',
                                      'maxlength' => '',
                                    ),
                                    array (
                                      'key' => 'field_57f7baa7defec',
                                      'label' => 'Valor',
                                      'name' => 'value',
                                      'type' => 'text',
                                      'instructions' => '',
                                      'required' => 0,
                                      'conditional_logic' => 0,
                                      'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                      ),
                                      'default_value' => '',
                                      'placeholder' => '',
                                      'prepend' => '',
                                      'append' => '',
                                      'maxlength' => '',
                                    ),
                                  ),
                                ),
                                array (
                                  'key' => 'field_57fa8106778f5',
                                  'label' => 'Lista Definida',
                                  'name' => 'lista_definida',
                                  'type' => 'flexible_content',
                                  'instructions' => '',
                                  'required' => 0,
                                  'conditional_logic' => array (
                                    array (
                                      array (
                                        'field' => 'field_57f7e26d5078e',
                                        'operator' => '==',
                                        'value' => 'lista',
                                      ),
                                    ),
                                  ),
                                  'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                  ),
                                  'button_label' => 'Add Lista',
                                  'min' => '',
                                  'max' => '',
                                  'layouts' => array (
                                    array (
                                      'key' => '57fa8b80b8f8f',
                                      'name' => 'nueva_lista',
                                      'label' => 'Nueva lista',
                                      'display' => 'block',
                                      'sub_fields' => array (
                                        array (
                                          'key' => 'field_57fa8122778f6',
                                          'label' => 'Titulo',
                                          'name' => 'titulo',
                                          'type' => 'text',
                                          'instructions' => '',
                                          'required' => 1,
                                          'conditional_logic' => 0,
                                          'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                          ),
                                          'default_value' => '',
                                          'placeholder' => '',
                                          'prepend' => '',
                                          'append' => '',
                                          'maxlength' => '',
                                        ),
                                        array (
                                          'key' => 'field_57fa8b9b465e3',
                                          'label' => 'valores',
                                          'name' => 'valores',
                                          'type' => 'repeater',
                                          'instructions' => '',
                                          'required' => 1,
                                          'conditional_logic' => 0,
                                          'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                          ),
                                          'collapsed' => '',
                                          'min' => '',
                                          'max' => '',
                                          'layout' => 'table',
                                          'button_label' => 'Add Valor',
                                          'sub_fields' => array (
                                            array (
                                              'key' => 'field_57fa8baf465e4',
                                              'label' => 'valor',
                                              'name' => 'valor',
                                              'type' => 'text',
                                              'instructions' => '',
                                              'required' => 1,
                                              'conditional_logic' => 0,
                                              'wrapper' => array (
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                              ),
                                              'default_value' => '',
                                              'placeholder' => '',
                                              'prepend' => '',
                                              'append' => '',
                                              'maxlength' => '',
                                            ),
                                          ),
                                        ),
                                      ),
                                      'min' => '0',
                                      'max' => '1',
                                    ),
                                  ),
                                ),
                              ),
                              'min' => '',
                              'max' => '',
                            ),
                          ),
                        ),
                      ),
                    ),
                  ),
                  'min' => '',
                  'max' => '',
                ),
              ),
            ),
          ),
          'min' => '',
          'max' => '',
        ),
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'page_parent',
        'operator' => '==',
        'value' => '10',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'acf_after_title',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => array (
    0 => 'custom_fields',
  ),
  'active' => 1,
  'description' => '',
));

endif;